version: '3'
services:
  eventure-backend:
    image: eventure-backend
    ports:
      - "8080:8080"
    environment:
      - CLOUDINARY_URL=cloudinary://724646329864838:BKftyqRp1tUO_RIqgFhL8gw240c@de7uimbtt